### ISSUE TITLE
Allow Messaging Offline Players 

### ISSUE THREAD

**Issue by Goinging** [MusiJVR/SimpleMsgPlugin#1]
Context: Our server needs a new messaging plugin seeing as the plugin we currently use https://www.spigotmc.org/resources/privatemessages-1-7-1-19.54026/. Is no longer being updated by its creator and doesn't work at least on the dev builds of paper 1.20.6. This one seems like a great match with a lot of these features being better than on the other plugin, however, you cannot message offline players using this plugin.

Feature: Adding the ability to message offline players and having the messages stored in a database with players being prompted whenever they next login that they have unread messages. Basically it ideally would work similarly to the plugin I attached.

**Comment by MusiJVR** [comment]
This is a good idea! I will implement this mechanic in the next version of the plugin 1.3.0, it will be released today or tomorrow on Modrinth

**Comment by MusiJVR** [comment]
Your idea has been implemented in the new version of the plugin 1.3.0!
You can already download from [Modrinth](https://modrinth.com/plugin/simplemsgplugin/version/1.3.0)
If you have new ideas/suggestions or find a bug, you can write to me on [Discord](https://discord.gg/xY8WJt7VGr) or [Issues](https://github.com/MusiJVR/SimpleMsgPlugin/issues)
Thanks for your feedback!

**Comment by Goinging** [comment]
Hi again, this is a great feature and it works almost perfectly! Could you however add an a config option to change the offline msg text/color?
![image](https://github.com/MusiJVR/SimpleMsgPlugin/assets/146245761/8369f97c-5907-442f-8da1-0f3481f4c19a)

**Comment by MusiJVR** [comment]
I forgot to add the pattern for this message to the config. Apologize. Today I will fix it and post it on Modrinth

**Comment by MusiJVR** [comment]
I fixed errors related to sending offline messages and setting up sound.
You can download the new version from [Modrinth](https://modrinth.com/plugin/simplemsgplugin/version/1.3.1)
Thanks for your feedback!
