### ISSUE TITLE
Add a Sound Volume Command / Option

### ISSUE THREAD

**Issue by Goinging** [MusiJVR/SimpleMsgPlugin#2]
Since the /csound command allows you to play any sound in the game, a lot are really load so it would be nice if people could choose the volume of the sounds. Instead of changing each sounds volume individually, it would be the same sound volume that would be applied to each sound.

**Comment by MusiJVR** [comment]
Thanks for the idea! I will add this in the next version of the plugin

**Comment by MusiJVR** [comment]
Your idea has been implemented in the new version of the plugin 1.3.0!
You can already download from [Modrinth](https://modrinth.com/plugin/simplemsgplugin/version/1.3.0)
If you have new ideas/suggestions or find a bug, you can write to me on [Discord](https://discord.gg/xY8WJt7VGr) or [Issues](https://github.com/MusiJVR/SimpleMsgPlugin/issues)
Thanks for your feedback!

**Comment by Goinging** [comment]
Thanks for implementing, although you just changed the pitch of the sound effects. not really the volume. At the default 50 most sounds don't really sound like the same sound effect and just sound slowed down.
