### ISSUE TITLE
Player Name Changes Are not Accounted For

### ISSUE THREAD

**Issue by Goinging** [MusiJVR/SimpleMsgPlugin#4]
Sorry for bothering you again, however, we are encountering a bug where players who change their usernames and rejoin the server can no longer be messaged. Their original names can be offline messaged still even though nobody owns an account with that name. What I am assuming is happening is that the database is recording each players username and UUID and setting them in stone together.

**Comment by MusiJVR** [comment]
Most likely yes, this is due to this. But this cannot be changed in any way, since the entire structure of the database will have to be changed. In theory, you can fix everything manually by editing the database.

**Comment by DevKilo1** [comment]
> Most likely yes, this is due to this. But this cannot be changed in any way, since the entire structure of the database will have to be changed. In theory, you can fix everything manually by editing the database.

I understand how it may be to develop such a large project and I also understand that you may have a certain file structure to keep everything organized. I'm not super experienced in plugin development, but fixing this issue should be as simple as switching from getting the player by username to getting the player by UUID. If the database containing the player's username, is absolutely necessary you could also update the player's username in the database with this so everything functions well.
