### ISSUE TITLE
Offline message placeholder doesn't work

### ISSUE THREAD

**Issue by Goinging** [MusiJVR/SimpleMsgPlugin#5]
![image](https://github.com/MusiJVR/SimpleMsgPlugin/assets/146245761/13185d9f-cc9b-4799-bcba-5612c63930da)
![image](https://github.com/MusiJVR/SimpleMsgPlugin/assets/146245761/fa091e9a-1b85-42f7-87e6-b5a0f7a52fa4)

Normal messages work, it is just offline messages that don't on the newest version.

**Comment by MusiJVR** [comment]
Write `%messages%` in `msgofflinepattern`. Everything should work.

**Comment by Goinging** [comment]
Yep, I have been manually copying everything from the old config files to the new ones because I know in the past this plugin doesn't update config files automatically. I didn't even see a difference between them and when I checked again last night I missed it as well.
