### ISSUE TITLE
Updating from 1.5.1 -> 1.6.1 Breaks the Database

### ISSUE THREAD

**Issue by Goinging** [MusiJVR/SimpleMsgPlugin#7]
Btw you changed the names that the plugin accepts in the database for columns and tables without making it so the plugin converts it automatically. Like for example you changed PlayerName -> player_name, but just updating the plugin won't make that change so it will just give an error.

**Comment by MusiJVR** [comment]
Yes, I know that such a problem will occur, but unfortunately I could not fix it. This can only be fixed by deleting the old database.

**Comment by Goinging** [comment]
nah I was able to download the database and edit the names of the columns and tables in a database editor so its fine. If its a known issue then that's whatever you may want to put that in the change log though
